"""mensaje de migración

Revision ID: 2639b264909d
Revises: 
Create Date: 2023-06-26 23:19:12.897909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2639b264909d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor_seccion', schema=None) as batch_op:
        batch_op.alter_column('profesor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('seccion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_seccion', sa.String(length=100), nullable=True))
        batch_op.drop_column('laboratorio')
        batch_op.drop_column('aula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aula', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('laboratorio', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('tipo_seccion')

    with op.batch_alter_table('profesor_seccion', schema=None) as batch_op:
        batch_op.alter_column('seccion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('profesor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
