"""mensaje de migración

Revision ID: c425e5923fb6
Revises: 2639b264909d
Create Date: 2023-06-27 23:33:39.974987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c425e5923fb6'
down_revision = '2639b264909d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aula', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('laboratorio', sa.String(length=100), nullable=True))
        batch_op.drop_column('tipo_seccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_seccion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('laboratorio')
        batch_op.drop_column('aula')

    # ### end Alembic commands ###
